dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: otel-collector
  description: OpenTelemetry Collector for the lalilulelo organization
  otelcol_version: "0.82.0"
  output_path: build

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.82.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.82.0
extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.82.0
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.82.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.82.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.82.0
